// Generated by gencpp from file basics/WordCount.msg
// DO NOT EDIT!


#ifndef BASICS_MESSAGE_WORDCOUNT_H
#define BASICS_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <basics/WordCountRequest.h>
#include <basics/WordCountResponse.h>


namespace basics
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace basics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basics::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::basics::WordCount&) { return value(); }
};

template<>
struct DataType< ::basics::WordCount > {
  static const char* value()
  {
    return "basics/WordCount";
  }

  static const char* value(const ::basics::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::basics::WordCountRequest> should match
// service_traits::MD5Sum< ::basics::WordCount >
template<>
struct MD5Sum< ::basics::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basics::WordCount >::value();
  }
  static const char* value(const ::basics::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basics::WordCountRequest> should match
// service_traits::DataType< ::basics::WordCount >
template<>
struct DataType< ::basics::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::basics::WordCount >::value();
  }
  static const char* value(const ::basics::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basics::WordCountResponse> should match
// service_traits::MD5Sum< ::basics::WordCount >
template<>
struct MD5Sum< ::basics::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basics::WordCount >::value();
  }
  static const char* value(const ::basics::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basics::WordCountResponse> should match
// service_traits::DataType< ::basics::WordCount >
template<>
struct DataType< ::basics::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::basics::WordCount >::value();
  }
  static const char* value(const ::basics::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASICS_MESSAGE_WORDCOUNT_H
